const DATA = {
  ingredients: [
    // 春
    { name: "たけのこ", seasons: ["春"] },
    { name: "菜の花", seasons: ["春"] },
    { name: "あさり", seasons: ["春"] },
    { name: "春キャベツ", seasons: ["春"] },
    { name: "新玉ねぎ", seasons: ["春"] },
    { name: "そら豆", seasons: ["春"] },
    { name: "グリーンピース", seasons: ["春"] },
    { name: "うど", seasons: ["春"] },
    { name: "新じゃがいも", seasons: ["春"] },
    { name: "桜えび", seasons: ["春"] },
    { name: "ふきのとう", seasons: ["春"] },
    { name: "スナップえんどう", seasons: ["春"] },
    { name: "新ごぼう", seasons: ["春"] },
    { name: "蛤", seasons: ["春"] },
    { name: "鯛", seasons: ["春"] },
    { name: "わかめ", seasons: ["春"] },
    { name: "木の芽", seasons: ["春"] },
    { name: "山椒の芽", seasons: ["春"] },
    // 夏
    { name: "トマト", seasons: ["夏"] },
    { name: "なす", seasons: ["夏"] },
    { name: "ズッキーニ", seasons: ["夏"] },
    { name: "とうもろこし", seasons: ["夏"] },
    { name: "枝豆", seasons: ["夏"] },
    { name: "オクラ", seasons: ["夏"] },
    { name: "ゴーヤ", seasons: ["夏"] },
    { name: "きゅうり", seasons: ["夏"] },
    { name: "すいか", seasons: ["夏"] },
    { name: "うなぎ", seasons: ["夏"] },
    { name: "あじ", seasons: ["夏"] },
    { name: "いわし", seasons: ["夏"] },
    { name: "冬瓜", seasons: ["夏"] },
    { name: "青じそ", seasons: ["夏"] },
    { name: "みょうが", seasons: ["夏"] },
    { name: "かぼちゃ", seasons: ["夏"] },
    { name: "ピーマン", seasons: ["夏"] },
    { name: "鱧", seasons: ["夏"] },
    { name: "穴子", seasons: ["夏"] },
    { name: "モロヘイヤ", seasons: ["夏"] },
    { name: "万願寺とうがらし", seasons: ["夏"] },
    { name: "空心菜", seasons: ["夏"] },
    // 秋
    { name: "まつたけ", seasons: ["秋"] },
    { name: "しいたけ", seasons: ["秋", "通年"] },
    { name: "さつまいも", seasons: ["秋"] },
    { name: "栗", seasons: ["秋"] },
    { name: "れんこん", seasons: ["秋"] },
    { name: "ぎんなん", seasons: ["秋"] },
    { name: "秋鮭", seasons: ["秋"] },
    { name: "さんま", seasons: ["秋"] },
    { name: "柿", seasons: ["秋"] },
    { name: "舞茸", seasons: ["秋"] },
    { name: "ゆり根", seasons: ["秋"] },
    { name: "かぶ", seasons: ["秋"] },
    { name: "ごぼう", seasons: ["秋"] },
    { name: "ひらたけ", seasons: ["秋"] },
    { name: "鯖", seasons: ["秋"] },
    { name: "いくら", seasons: ["秋"] },
    { name: "じねんじょ", seasons: ["秋"] },
    { name: "海老芋", seasons: ["秋"] },
    { name: "小芋", seasons: ["秋"] },
    { name: "むかご", seasons: ["秋"] },
    // 冬
    { name: "白菜", seasons: ["冬"] },
    { name: "大根", seasons: ["冬", "通年"] },
    { name: "ねぎ", seasons: ["冬"] },
    { name: "ほうれん草", seasons: ["冬"] },
    { name: "カリフラワー", seasons: ["冬"] },
    { name: "ブロッコリー", seasons: ["冬"] },
    { name: "牡蠣", seasons: ["冬"] },
    { name: "たら", seasons: ["冬"] },
    { name: "ぶり", seasons: ["冬"] },
    { name: "金柑", seasons: ["冬"] },
    { name: "春菊", seasons: ["冬"] },
    { name: "小松菜", seasons: ["冬"] },
    { name: "水菜", seasons: ["冬"] },
    { name: "芽キャベツ", seasons: ["冬"] },
    { name: "金目鯛", seasons: ["冬"] },
    { name: "蟹", seasons: ["冬"] },
    { name: "あんこう", seasons: ["冬"] },
    { name: "菊芋", seasons: ["冬"] },
    { name: "ふぐ", seasons: ["冬"] },
    { name: "聖護院大根", seasons: ["冬"] },
    // 通年・肉類
    { name: "鶏もも肉", seasons: ["通年"] },
    { name: "豚バラ", seasons: ["通年"] },
    { name: "牛ヒレ", seasons: ["通年"] },
    { name: "豚ロース", seasons: ["通年"] },
    { name: "牛タン", seasons: ["通年"] },
    { name: "鴨肉", seasons: ["通年"] },
    { name: "ラム肉", seasons: ["通年"] },
    { name: "鶏胸肉", seasons: ["通年"] },
    { name: "鶏手羽先", seasons: ["通年"] },
    { name: "豚肩ロース", seasons: ["通年"] },
    { name: "牛バラ肉", seasons: ["通年"] },
    { name: "合鴨", seasons: ["通年"] },
    { name: "牛すね肉", seasons: ["通年"] },
    // 通年・魚介
    { name: "サーモン", seasons: ["通年"] },
    { name: "エビ", seasons: ["通年"] },
    { name: "イカ", seasons: ["通年"] },
    { name: "帆立", seasons: ["通年"] },
    { name: "タコ", seasons: ["通年"] },
    { name: "銀鱈", seasons: ["通年"] },
    { name: "メカジキ", seasons: ["通年"] },
    { name: "ホタルイカ", seasons: ["通年"] },
    { name: "うに", seasons: ["通年"] },
    { name: "白子", seasons: ["通年"] },
    { name: "鮭", seasons: ["通年"] },
    // 通年・きのこ
    { name: "マッシュルーム", seasons: ["通年"] },
    { name: "エリンギ", seasons: ["通年"] },
    { name: "きくらげ", seasons: ["通年"] },
    { name: "えのき", seasons: ["通年"] },
    { name: "なめこ", seasons: ["通年"] },
    { name: "ぶなしめじ", seasons: ["通年"] },
    // 通年・野菜
    { name: "豆腐", seasons: ["通年"] },
    { name: "卵", seasons: ["通年"] },
    { name: "玉ねぎ", seasons: ["通年"] },
    { name: "にんじん", seasons: ["通年"] },
    { name: "じゃがいも", seasons: ["通年"] },
    { name: "にんにく", seasons: ["通年"] },
    { name: "しょうが", seasons: ["通年"] },
    { name: "パプリカ", seasons: ["通年"] },
    { name: "アボカド", seasons: ["通年"] },
    { name: "長芋", seasons: ["通年"] },
    { name: "里芋", seasons: ["通年"] },
    { name: "山芋", seasons: ["通年"] },
    { name: "ルッコラ", seasons: ["通年"] },
    { name: "ケール", seasons: ["通年"] },
    { name: "バジル", seasons: ["通年"] },
    { name: "パクチー", seasons: ["通年"] },
    { name: "セロリ", seasons: ["通年"] },
    { name: "フェンネル", seasons: ["通年"] },
    { name: "赤玉ねぎ", seasons: ["通年"] },
    { name: "豆苗", seasons: ["通年"] },
    { name: "かいわれ", seasons: ["通年"] },
    { name: "ラディッシュ", seasons: ["通年"] },
    { name: "ビーツ", seasons: ["通年"] },
    // 通年・加工品
    { name: "厚揚げ", seasons: ["通年"] },
    { name: "こんにゃく", seasons: ["通年"] },
    { name: "高野豆腐", seasons: ["通年"] },
    { name: "油揚げ", seasons: ["通年"] },
    { name: "春雨", seasons: ["通年"] },
    // 通年・香味・風味
    { name: "柚子", seasons: ["通年"] },
    { name: "梅", seasons: ["通年"] },
    { name: "酒粕", seasons: ["通年"] },
    { name: "レモン", seasons: ["通年"] },
    { name: "黒にんにく", seasons: ["通年"] },
    { name: "花椒", seasons: ["通年"] },
    { name: "山椒", seasons: ["通年"] },
    { name: "唐辛子", seasons: ["通年"] },
    { name: "チーズ", seasons: ["通年"] },
    { name: "生クリーム", seasons: ["通年"] },
    { name: "バター", seasons: ["通年"] },
    { name: "くるみ", seasons: ["通年"] },
    { name: "松の実", seasons: ["通年"] },
    { name: "白ごま", seasons: ["通年"] },
    // 春（追加）
    { name: "アスパラガス", seasons: ["春"] },
    { name: "たらの芽", seasons: ["春"] },
    { name: "わらび", seasons: ["春"] },
    { name: "かつお", seasons: ["春"] },
    { name: "白魚", seasons: ["春"] },
    // 夏（追加）
    { name: "鮎", seasons: ["夏"] },
    { name: "太刀魚", seasons: ["夏"] },
    { name: "かます", seasons: ["夏"] },
    { name: "赤じそ", seasons: ["夏"] },
    { name: "とびうお", seasons: ["夏"] },
    // 秋（追加）
    { name: "りんご", seasons: ["秋"] },
    { name: "いちじく", seasons: ["秋"] },
    { name: "洋梨", seasons: ["秋"] },
    { name: "食用菊", seasons: ["秋"] },
    { name: "かぼす", seasons: ["秋"] },
    // 冬（追加）
    { name: "のどぐろ", seasons: ["冬"] },
    { name: "さわら", seasons: ["冬"] },
    { name: "数の子", seasons: ["冬"] },
    { name: "甘エビ", seasons: ["冬"] },
    { name: "子持ちこんぶ", seasons: ["冬"] },
    // 通年・肉類（追加）
    { name: "牛サーロイン", seasons: ["通年"] },
    { name: "豚ヒレ", seasons: ["通年"] },
    { name: "鶏ささみ", seasons: ["通年"] },
    { name: "鹿肉", seasons: ["通年"] },
    { name: "猪肉", seasons: ["通年"] },
    { name: "仔羊", seasons: ["通年"] },
    { name: "鶏レバー", seasons: ["通年"] },
    { name: "砂肝", seasons: ["通年"] },
    // 通年・魚介（追加）
    { name: "まぐろ", seasons: ["通年"] },
    { name: "ヒラメ", seasons: ["通年"] },
    { name: "甘鯛", seasons: ["通年"] },
    { name: "しまあじ", seasons: ["通年"] },
    { name: "カレイ", seasons: ["通年"] },
    { name: "めばる", seasons: ["通年"] },
    { name: "キンキ", seasons: ["通年"] },
    { name: "真鯛", seasons: ["通年"] },
    { name: "赤エビ", seasons: ["通年"] },
    { name: "毛ガニ", seasons: ["通年"] },
    // 通年・野菜・ハーブ（追加）
    { name: "三つ葉", seasons: ["通年"] },
    { name: "わさび", seasons: ["通年"] },
    { name: "九条ねぎ", seasons: ["通年"] },
    { name: "芽ねぎ", seasons: ["通年"] },
    { name: "パセリ", seasons: ["通年"] },
    { name: "ディル", seasons: ["通年"] },
    { name: "タイム", seasons: ["通年"] },
    { name: "ローズマリー", seasons: ["通年"] },
    { name: "オレガノ", seasons: ["通年"] },
    { name: "レモングラス", seasons: ["通年"] },
    { name: "チコリ", seasons: ["通年"] },
    { name: "トレビス", seasons: ["通年"] },
    { name: "紫キャベツ", seasons: ["通年"] },
    { name: "ロマネスコ", seasons: ["通年"] },
    { name: "ポロねぎ", seasons: ["通年"] },
    { name: "ベビーリーフ", seasons: ["通年"] },
    { name: "サンチュ", seasons: ["通年"] },
    { name: "えごまの葉", seasons: ["通年"] },
    { name: "花ニラ", seasons: ["通年"] },
    { name: "黒オリーブ", seasons: ["通年"] },
    { name: "ケイパー", seasons: ["通年"] },
    { name: "グリーンアスパラ", seasons: ["通年"] },
    { name: "ホワイトアスパラ", seasons: ["通年"] },
    { name: "赤唐辛子", seasons: ["通年"] },
    // 通年・果物・ナッツ（追加）
    { name: "いちご", seasons: ["通年"] },
    { name: "もも", seasons: ["通年"] },
    { name: "マンゴー", seasons: ["通年"] },
    { name: "パイナップル", seasons: ["通年"] },
    { name: "オレンジ", seasons: ["通年"] },
    { name: "グレープフルーツ", seasons: ["通年"] },
    { name: "ライム", seasons: ["通年"] },
    { name: "すだち", seasons: ["通年"] },
    { name: "アーモンド", seasons: ["通年"] },
    { name: "カシューナッツ", seasons: ["通年"] },
    { name: "ヘーゼルナッツ", seasons: ["通年"] },
    { name: "マカダミアナッツ", seasons: ["通年"] },
    { name: "ピスタチオ", seasons: ["通年"] },
    { name: "黒ごま", seasons: ["通年"] },
    { name: "なつめ", seasons: ["通年"] },
    // 通年・豆・穀物（追加）
    { name: "レンズ豆", seasons: ["通年"] },
    { name: "ひよこ豆", seasons: ["通年"] },
    { name: "白いんげん豆", seasons: ["通年"] },
    { name: "黒豆", seasons: ["通年"] },
    { name: "小豆", seasons: ["通年"] },
    { name: "そば粉", seasons: ["通年"] },
    { name: "米粉", seasons: ["通年"] },
    // 通年・乾物・発酵・特殊素材（追加）
    { name: "昆布", seasons: ["通年"] },
    { name: "かつおぶし", seasons: ["通年"] },
    { name: "生ハム", seasons: ["通年"] },
    { name: "アンチョビ", seasons: ["通年"] },
    { name: "干し貝柱", seasons: ["通年"] },
    { name: "塩麹", seasons: ["通年"] },
    { name: "醤油麹", seasons: ["通年"] },
    { name: "フォアグラ", seasons: ["通年"] },
    { name: "黒トリュフ", seasons: ["通年"] },
    { name: "キャビア", seasons: ["通年"] },
    { name: "パンチェッタ", seasons: ["通年"] },
    { name: "八角", seasons: ["通年"] },
    { name: "海苔", seasons: ["通年"] },
    { name: "とろろ昆布", seasons: ["通年"] },
    { name: "甘酒", seasons: ["通年"] },
  ],

  dishes: [
    // 和
    { name: "炊き合わせ", origins: ["和"] },
    { name: "煮浸し", origins: ["和"] },
    { name: "天ぷら", origins: ["和"] },
    { name: "だし巻き", origins: ["和"] },
    { name: "和え物", origins: ["和"] },
    { name: "酢の物", origins: ["和"] },
    { name: "焼き浸し", origins: ["和"] },
    { name: "土鍋ご飯", origins: ["和"] },
    { name: "蒸し料理", origins: ["和"] },
    { name: "揚げ出し", origins: ["和"] },
    { name: "南蛮漬け", origins: ["和"] },
    { name: "しゃぶしゃぶ", origins: ["和"] },
    { name: "照り焼き", origins: ["和"] },
    { name: "みそ汁", origins: ["和"] },
    { name: "茶碗蒸し", origins: ["和"] },
    { name: "塩焼き", origins: ["和"] },
    { name: "西京焼き", origins: ["和"] },
    { name: "幽庵焼き", origins: ["和"] },
    { name: "竜田揚げ", origins: ["和"] },
    { name: "磯辺揚げ", origins: ["和"] },
    { name: "田楽", origins: ["和"] },
    { name: "お浸し", origins: ["和"] },
    { name: "酒蒸し", origins: ["和"] },
    { name: "塩麹漬け", origins: ["和"] },
    { name: "雑炊", origins: ["和"] },
    { name: "すき焼き", origins: ["和"] },
    { name: "唐揚げ", origins: ["和"] },
    { name: "みぞれ煮", origins: ["和"] },
    { name: "粕汁仕立て", origins: ["和"] },
    { name: "有馬煮", origins: ["和"] },
    // 洋（フレンチ・イタリアン）
    { name: "カルパッチョ", origins: ["洋", "伊"] },
    { name: "グラタン", origins: ["洋", "仏"] },
    { name: "ムニエル", origins: ["洋", "仏"] },
    { name: "ポワレ", origins: ["洋", "仏"] },
    { name: "ブイヤベース", origins: ["洋", "仏"] },
    { name: "ラグー", origins: ["洋", "伊"] },
    { name: "リゾット", origins: ["洋", "伊"] },
    { name: "カポナータ", origins: ["洋", "伊"] },
    { name: "アクアパッツァ", origins: ["洋", "伊"] },
    { name: "ピカタ", origins: ["洋", "伊"] },
    { name: "テリーヌ", origins: ["洋", "仏"] },
    { name: "キッシュ", origins: ["洋", "仏"] },
    { name: "ガレット", origins: ["洋", "仏"] },
    { name: "ビスク", origins: ["洋", "仏"] },
    { name: "コンフィ", origins: ["洋", "仏"] },
    { name: "マリネ", origins: ["洋"] },
    { name: "フリット", origins: ["洋", "伊"] },
    { name: "カルボナーラ", origins: ["洋", "伊"] },
    { name: "パスタ", origins: ["洋", "伊"] },
    { name: "ロースト", origins: ["洋"] },
    { name: "ソテー", origins: ["洋"] },
    { name: "フリカッセ", origins: ["洋", "仏"] },
    { name: "ポトフ", origins: ["洋", "仏"] },
    { name: "タルタル", origins: ["洋", "仏"] },
    { name: "ガスパチョ", origins: ["洋"] },
    { name: "ニョッキ", origins: ["洋", "伊"] },
    { name: "ラザニア", origins: ["洋", "伊"] },
    { name: "ミネストローネ", origins: ["洋", "伊"] },
    { name: "オムレツ", origins: ["洋", "仏"] },
    { name: "クロケット", origins: ["洋"] },
    { name: "エスカベッシュ", origins: ["洋"] },
    { name: "ブレゼ", origins: ["洋", "仏"] },
    { name: "グリル", origins: ["洋"] },
    { name: "タリアータ", origins: ["洋", "伊"] },
    { name: "ヴィシソワーズ", origins: ["洋", "仏"] },
    // 中
    { name: "炒め物", origins: ["中"] },
    { name: "餃子", origins: ["中"] },
    { name: "春巻き", origins: ["中"] },
    { name: "麻婆", origins: ["中"] },
    { name: "肉まん", origins: ["中"] },
    { name: "チャーハン", origins: ["中"] },
    { name: "八宝菜", origins: ["中"] },
    { name: "酢豚", origins: ["中"] },
    { name: "蒸し餃子", origins: ["中"] },
    { name: "小籠包", origins: ["中"] },
    { name: "棒棒鶏", origins: ["中"] },
    { name: "回鍋肉", origins: ["中"] },
    { name: "青椒肉絲", origins: ["中"] },
    { name: "担々仕立て", origins: ["中"] },
    { name: "ワンタン", origins: ["中"] },
    // アジア
    { name: "カレー", origins: ["アジア"] },
    { name: "フォー", origins: ["アジア"] },
    { name: "バインミー", origins: ["アジア"] },
    { name: "ガパオ", origins: ["アジア"] },
    { name: "ラープ", origins: ["アジア"] },
    { name: "トムヤム", origins: ["アジア"] },
    { name: "サテー", origins: ["アジア"] },
    { name: "グリーンカレー", origins: ["アジア"] },
    { name: "レッドカレー", origins: ["アジア"] },
    { name: "パッタイ", origins: ["アジア"] },
    { name: "バオ", origins: ["アジア"] },
    { name: "ラクサ", origins: ["アジア"] },
    { name: "ナシゴレン", origins: ["アジア"] },
  ],

  seasons: ["春", "夏", "秋", "冬"],
  origins: ["和", "洋", "仏", "伊", "中", "アジア"],
};
