const DATA = {
  ingredients: [
    // 春
    { name: "たけのこ", seasons: ["春"] },
    { name: "菜の花", seasons: ["春"] },
    { name: "あさり", seasons: ["春"] },
    { name: "春キャベツ", seasons: ["春"] },
    { name: "新玉ねぎ", seasons: ["春"] },
    { name: "そら豆", seasons: ["春"] },
    { name: "グリーンピース", seasons: ["春"] },
    { name: "うど", seasons: ["春"] },
    { name: "新じゃがいも", seasons: ["春"] },
    { name: "桜えび", seasons: ["春"] },
    // 夏
    { name: "トマト", seasons: ["夏"] },
    { name: "なす", seasons: ["夏"] },
    { name: "ズッキーニ", seasons: ["夏"] },
    { name: "とうもろこし", seasons: ["夏"] },
    { name: "枝豆", seasons: ["夏"] },
    { name: "オクラ", seasons: ["夏"] },
    { name: "ゴーヤ", seasons: ["夏"] },
    { name: "きゅうり", seasons: ["夏"] },
    { name: "すいか", seasons: ["夏"] },
    { name: "うなぎ", seasons: ["夏"] },
    { name: "あじ", seasons: ["夏"] },
    { name: "いわし", seasons: ["夏"] },
    // 秋
    { name: "まつたけ", seasons: ["秋"] },
    { name: "しいたけ", seasons: ["秋", "通年"] },
    { name: "さつまいも", seasons: ["秋"] },
    { name: "栗", seasons: ["秋"] },
    { name: "れんこん", seasons: ["秋"] },
    { name: "ぎんなん", seasons: ["秋"] },
    { name: "秋鮭", seasons: ["秋"] },
    { name: "さんま", seasons: ["秋"] },
    { name: "柿", seasons: ["秋"] },
    { name: "舞茸", seasons: ["秋"] },
    // 冬
    { name: "白菜", seasons: ["冬"] },
    { name: "大根", seasons: ["冬", "通年"] },
    { name: "ねぎ", seasons: ["冬"] },
    { name: "ほうれん草", seasons: ["冬"] },
    { name: "カリフラワー", seasons: ["冬"] },
    { name: "ブロッコリー", seasons: ["冬"] },
    { name: "牡蠣", seasons: ["冬"] },
    { name: "たら", seasons: ["冬"] },
    { name: "ぶり", seasons: ["冬"] },
    { name: "金柑", seasons: ["冬"] },
    // 通年
    { name: "鶏もも肉", seasons: ["通年"] },
    { name: "豚バラ", seasons: ["通年"] },
    { name: "牛ヒレ", seasons: ["通年"] },
    { name: "豆腐", seasons: ["通年"] },
    { name: "卵", seasons: ["通年"] },
    { name: "玉ねぎ", seasons: ["通年"] },
    { name: "にんじん", seasons: ["通年"] },
    { name: "じゃがいも", seasons: ["通年"] },
    { name: "にんにく", seasons: ["通年"] },
    { name: "しょうが", seasons: ["通年"] },
    { name: "サーモン", seasons: ["通年"] },
    { name: "エビ", seasons: ["通年"] },
    { name: "イカ", seasons: ["通年"] },
    { name: "帆立", seasons: ["通年"] },
    { name: "マッシュルーム", seasons: ["通年"] },
    { name: "パプリカ", seasons: ["通年"] },
    { name: "アボカド", seasons: ["通年"] },
  ],

  dishes: [
    // 和
    { name: "炊き合わせ", origins: ["和"] },
    { name: "煮浸し", origins: ["和"] },
    { name: "天ぷら", origins: ["和"] },
    { name: "だし巻き", origins: ["和"] },
    { name: "和え物", origins: ["和"] },
    { name: "酢の物", origins: ["和"] },
    { name: "焼き浸し", origins: ["和"] },
    { name: "土鍋ご飯", origins: ["和"] },
    { name: "蒸し料理", origins: ["和"] },
    { name: "揚げ出し", origins: ["和"] },
    { name: "南蛮漬け", origins: ["和"] },
    { name: "しゃぶしゃぶ", origins: ["和"] },
    { name: "照り焼き", origins: ["和"] },
    { name: "みそ汁", origins: ["和"] },
    { name: "茶碗蒸し", origins: ["和"] },
    // 洋（フレンチ・イタリアン）
    { name: "カルパッチョ", origins: ["洋", "伊"] },
    { name: "グラタン", origins: ["洋", "仏"] },
    { name: "ムニエル", origins: ["洋", "仏"] },
    { name: "ポワレ", origins: ["洋", "仏"] },
    { name: "ブイヤベース", origins: ["洋", "仏"] },
    { name: "ラグー", origins: ["洋", "伊"] },
    { name: "リゾット", origins: ["洋", "伊"] },
    { name: "カポナータ", origins: ["洋", "伊"] },
    { name: "アクアパッツァ", origins: ["洋", "伊"] },
    { name: "ピカタ", origins: ["洋", "伊"] },
    { name: "テリーヌ", origins: ["洋", "仏"] },
    { name: "キッシュ", origins: ["洋", "仏"] },
    { name: "ガレット", origins: ["洋", "仏"] },
    { name: "ビスク", origins: ["洋", "仏"] },
    { name: "コンフィ", origins: ["洋", "仏"] },
    { name: "マリネ", origins: ["洋"] },
    { name: "フリット", origins: ["洋", "伊"] },
    { name: "カルボナーラ", origins: ["洋", "伊"] },
    { name: "パスタ", origins: ["洋", "伊"] },
    // 中
    { name: "炒め物", origins: ["中"] },
    { name: "餃子", origins: ["中"] },
    { name: "春巻き", origins: ["中"] },
    { name: "麻婆", origins: ["中"] },
    { name: "肉まん", origins: ["中"] },
    { name: "チャーハン", origins: ["中"] },
    { name: "八宝菜", origins: ["中"] },
    { name: "酢豚", origins: ["中"] },
    // アジア
    { name: "カレー", origins: ["アジア"] },
    { name: "フォー", origins: ["アジア"] },
    { name: "バインミー", origins: ["アジア"] },
    { name: "ガパオ", origins: ["アジア"] },
    { name: "ラープ", origins: ["アジア"] },
    { name: "トムヤム", origins: ["アジア"] },
    { name: "サテー", origins: ["アジア"] },
  ],

  seasons: ["春", "夏", "秋", "冬"],
  origins: ["和", "洋", "仏", "伊", "中", "アジア"],
};
