const DATA = {
  ingredients: [
    // 春
    { name: "たけのこ",           seasons: ["春"],       category: "野菜",         sub: "根菜" },
    { name: "菜の花",             seasons: ["春"],       category: "野菜",         sub: "花野菜" },
    { name: "あさり",             seasons: ["春"],       category: "魚介",         sub: "貝類" },
    { name: "春キャベツ",         seasons: ["春"],       category: "野菜",         sub: "葉野菜" },
    { name: "新玉ねぎ",           seasons: ["春"],       category: "野菜",         sub: "根菜" },
    { name: "そら豆",             seasons: ["春"],       category: "野菜",         sub: "豆・えんどう" },
    { name: "グリーンピース",     seasons: ["春"],       category: "野菜",         sub: "豆・えんどう" },
    { name: "うど",               seasons: ["春"],       category: "野菜",         sub: "根菜" },
    { name: "新じゃがいも",       seasons: ["春"],       category: "野菜",         sub: "根菜" },
    { name: "桜えび",             seasons: ["春"],       category: "魚介",         sub: "甲殻類" },
    { name: "ふきのとう",         seasons: ["春"],       category: "野菜",         sub: "葉野菜" },
    { name: "スナップえんどう",   seasons: ["春"],       category: "野菜",         sub: "豆・えんどう" },
    { name: "新ごぼう",           seasons: ["春"],       category: "野菜",         sub: "根菜" },
    { name: "蛤",                 seasons: ["春"],       category: "魚介",         sub: "貝類" },
    { name: "鯛",                 seasons: ["春"],       category: "魚介",         sub: "魚" },
    { name: "わかめ",             seasons: ["春"],       category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "木の芽",             seasons: ["春"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "山椒の芽",           seasons: ["春"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "アスパラガス",       seasons: ["春"],       category: "野菜",         sub: "花野菜" },
    { name: "たらの芽",           seasons: ["春"],       category: "野菜",         sub: "葉野菜" },
    { name: "わらび",             seasons: ["春"],       category: "野菜",         sub: "葉野菜" },
    { name: "かつお",             seasons: ["春"],       category: "魚介",         sub: "魚" },
    { name: "白魚",               seasons: ["春"],       category: "魚介",         sub: "魚" },
    // 夏
    { name: "トマト",             seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "なす",               seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "ズッキーニ",         seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "とうもろこし",       seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "枝豆",               seasons: ["夏"],       category: "野菜",         sub: "豆・えんどう" },
    { name: "オクラ",             seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "ゴーヤ",             seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "きゅうり",           seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "すいか",             seasons: ["夏"],       category: "果物",         sub: null },
    { name: "うなぎ",             seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "あじ",               seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "いわし",             seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "冬瓜",               seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "青じそ",             seasons: ["夏"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "みょうが",           seasons: ["夏"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "かぼちゃ",           seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "ピーマン",           seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "鱧",                 seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "穴子",               seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "モロヘイヤ",         seasons: ["夏"],       category: "野菜",         sub: "葉野菜" },
    { name: "万願寺とうがらし",   seasons: ["夏"],       category: "野菜",         sub: "果実野菜" },
    { name: "空心菜",             seasons: ["夏"],       category: "野菜",         sub: "葉野菜" },
    { name: "鮎",                 seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "太刀魚",             seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "かます",             seasons: ["夏"],       category: "魚介",         sub: "魚" },
    { name: "赤じそ",             seasons: ["夏"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "とびうお",           seasons: ["夏"],       category: "魚介",         sub: "魚" },
    // 秋
    { name: "まつたけ",           seasons: ["秋"],       category: "きのこ",       sub: null },
    { name: "しいたけ",           seasons: ["秋", "通年"], category: "きのこ",     sub: null },
    { name: "さつまいも",         seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "栗",                 seasons: ["秋"],       category: "果物",         sub: null },
    { name: "れんこん",           seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "ぎんなん",           seasons: ["秋"],       category: "ナッツ",       sub: null },
    { name: "秋鮭",               seasons: ["秋"],       category: "魚介",         sub: "魚" },
    { name: "さんま",             seasons: ["秋"],       category: "魚介",         sub: "魚" },
    { name: "柿",                 seasons: ["秋"],       category: "果物",         sub: null },
    { name: "舞茸",               seasons: ["秋"],       category: "きのこ",       sub: null },
    { name: "ゆり根",             seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "かぶ",               seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "ごぼう",             seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "ひらたけ",           seasons: ["秋"],       category: "きのこ",       sub: null },
    { name: "鯖",                 seasons: ["秋"],       category: "魚介",         sub: "魚" },
    { name: "いくら",             seasons: ["秋"],       category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "じねんじょ",         seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "海老芋",             seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "小芋",               seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "むかご",             seasons: ["秋"],       category: "野菜",         sub: "根菜" },
    { name: "りんご",             seasons: ["秋"],       category: "果物",         sub: null },
    { name: "いちじく",           seasons: ["秋"],       category: "果物",         sub: null },
    { name: "洋梨",               seasons: ["秋"],       category: "果物",         sub: null },
    { name: "食用菊",             seasons: ["秋"],       category: "野菜",         sub: "花野菜" },
    { name: "かぼす",             seasons: ["秋"],       category: "スパイス・ハーブ", sub: "香味・薬味" },
    // 冬
    { name: "白菜",               seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "大根",               seasons: ["冬", "通年"], category: "野菜",       sub: "根菜" },
    { name: "ねぎ",               seasons: ["冬"],       category: "野菜",         sub: "根菜" },
    { name: "ほうれん草",         seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "カリフラワー",       seasons: ["冬"],       category: "野菜",         sub: "花野菜" },
    { name: "ブロッコリー",       seasons: ["冬"],       category: "野菜",         sub: "花野菜" },
    { name: "牡蠣",               seasons: ["冬"],       category: "魚介",         sub: "貝類" },
    { name: "たら",               seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "ぶり",               seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "金柑",               seasons: ["冬"],       category: "果物",         sub: null },
    { name: "春菊",               seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "小松菜",             seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "水菜",               seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "芽キャベツ",         seasons: ["冬"],       category: "野菜",         sub: "葉野菜" },
    { name: "金目鯛",             seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "蟹",                 seasons: ["冬"],       category: "魚介",         sub: "甲殻類" },
    { name: "あんこう",           seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "菊芋",               seasons: ["冬"],       category: "野菜",         sub: "根菜" },
    { name: "ふぐ",               seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "聖護院大根",         seasons: ["冬"],       category: "野菜",         sub: "根菜" },
    { name: "のどぐろ",           seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "さわら",             seasons: ["冬"],       category: "魚介",         sub: "魚" },
    { name: "数の子",             seasons: ["冬"],       category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "甘エビ",             seasons: ["冬"],       category: "魚介",         sub: "甲殻類" },
    { name: "子持ちこんぶ",       seasons: ["冬"],       category: "加工品・乾物", sub: "乾物・だし素材" },
    // 通年・肉類
    { name: "鶏もも肉",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "豚バラ",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "牛ヒレ",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "豚ロース",           seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "牛タン",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "鴨肉",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "ラム肉",             seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "鶏胸肉",             seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏手羽先",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "豚肩ロース",         seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "牛バラ肉",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "合鴨",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "牛すね肉",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛サーロイン",       seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "豚ヒレ",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "鶏ささみ",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鹿肉",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "猪肉",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "仔羊",               seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "鶏レバー",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "砂肝",               seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "牛リブロース",       seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛肩ロース",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛モモ",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛イチボ",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ランプ",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ミスジ",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ザブトン",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛シンタマ",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛カイノミ",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ハラミ",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛テール",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ほほ肉",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛骨髄",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ハツ",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛レバー",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛ミノ",             seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛センマイ",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛テッポウ",         seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "牛タン元",           seasons: ["通年"],     category: "肉",           sub: "牛" },
    { name: "豚もも",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚スペアリブ",       seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚頬肉",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚タン",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚レバー",           seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚足",               seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚ハツ",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚軟骨",             seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "豚耳",               seasons: ["通年"],     category: "肉",           sub: "豚" },
    { name: "鶏手羽元",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏手羽中",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏ぼんじり",         seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏皮",               seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏ハツ",             seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏せせり",           seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "鶏ソリレス",         seasons: ["通年"],     category: "肉",           sub: "鶏" },
    { name: "ラムチョップ",       seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "ラムレッグ",         seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "ラムラック",         seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "馬肉",               seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "うずら",             seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "鳩肉",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "ホロホロ鳥",         seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    { name: "兎肉",               seasons: ["通年"],     category: "肉",           sub: "ジビエ" },
    // 通年・魚介
    { name: "サーモン",           seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "エビ",               seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "イカ",               seasons: ["通年"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "帆立",               seasons: ["通年"],     category: "魚介",         sub: "貝類" },
    { name: "タコ",               seasons: ["通年"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "銀鱈",               seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "メカジキ",           seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "ホタルイカ",         seasons: ["春"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "うに",               seasons: ["通年"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "白子",               seasons: ["通年"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "鮭",                 seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "まぐろ",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "ヒラメ",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "甘鯛",               seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "しまあじ",           seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "カレイ",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "めばる",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "キンキ",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "真鯛",               seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "赤エビ",             seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "毛ガニ",             seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "トラウトサーモン",   seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "縞鯵",               seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "フエダイ",           seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "スズキ",             seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "黒鯛",               seasons: ["通年"],     category: "魚介",         sub: "魚" },
    { name: "ズワイガニ",         seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "車海老",             seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "ボタンエビ",         seasons: ["通年"],     category: "魚介",         sub: "甲殻類" },
    { name: "つぶ貝",             seasons: ["通年"],     category: "魚介",         sub: "貝類" },
    { name: "赤貝",               seasons: ["通年"],     category: "魚介",         sub: "貝類" },
    // 通年・きのこ
    { name: "マッシュルーム",     seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "エリンギ",           seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "きくらげ",           seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "えのき",             seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "なめこ",             seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "ぶなしめじ",         seasons: ["通年"],     category: "きのこ",       sub: null },
    // 通年・野菜
    { name: "豆腐",               seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "卵",                 seasons: ["通年"],     category: "加工品・乾物", sub: "乳製品" },
    { name: "玉ねぎ",             seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "にんじん",           seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "じゃがいも",         seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "にんにく",           seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "しょうが",           seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "パプリカ",           seasons: ["通年"],     category: "野菜",         sub: "果実野菜" },
    { name: "アボカド",           seasons: ["通年"],     category: "果物",         sub: null },
    { name: "長芋",               seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "里芋",               seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "山芋",               seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "ルッコラ",           seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "ケール",             seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "バジル",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "パクチー",           seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "セロリ",             seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "フェンネル",         seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "赤玉ねぎ",           seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "豆苗",               seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "かいわれ",           seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "ラディッシュ",       seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "ビーツ",             seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "三つ葉",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "わさび",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "九条ねぎ",           seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "芽ねぎ",             seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "パセリ",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "ディル",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "タイム",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "ローズマリー",       seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "オレガノ",           seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "レモングラス",       seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "チコリ",             seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "トレビス",           seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "紫キャベツ",         seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "ロマネスコ",         seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "ポロねぎ",           seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "ベビーリーフ",       seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "サンチュ",           seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "えごまの葉",         seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "花ニラ",             seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "黒オリーブ",         seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "ケイパー",           seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "グリーンアスパラ",   seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "ホワイトアスパラ",   seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "赤唐辛子",           seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    { name: "紫芋",               seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "紅芯大根",           seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "黒にんじん",         seasons: ["通年"],     category: "野菜",         sub: "根菜" },
    { name: "ロメインレタス",     seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "フリルレタス",       seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "水耕栽培レタス",     seasons: ["通年"],     category: "野菜",         sub: "葉野菜" },
    { name: "ズッキーニ花",       seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "エディブルフラワー", seasons: ["通年"],     category: "野菜",         sub: "花野菜" },
    { name: "マイクロハーブ",     seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "チャービル",         seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "エストラゴン",       seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "セージ",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "マジョラム",         seasons: ["通年"],     category: "スパイス・ハーブ", sub: "ハーブ" },
    { name: "コリアンダーシード", seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    // 通年・加工品
    { name: "厚揚げ",             seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "こんにゃく",         seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "高野豆腐",           seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "油揚げ",             seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "春雨",               seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    // 通年・香味・風味
    { name: "柚子",               seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "梅",                 seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "酒粕",               seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "レモン",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "黒にんにく",         seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "花椒",               seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    { name: "山椒",               seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    { name: "唐辛子",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    { name: "チーズ",             seasons: ["通年"],     category: "加工品・乾物", sub: "乳製品" },
    { name: "生クリーム",         seasons: ["通年"],     category: "加工品・乾物", sub: "乳製品" },
    { name: "バター",             seasons: ["通年"],     category: "加工品・乾物", sub: "乳製品" },
    { name: "くるみ",             seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "松の実",             seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "白ごま",             seasons: ["通年"],     category: "ナッツ",       sub: null },
    // 通年・果物・ナッツ
    { name: "いちご",             seasons: ["通年"],     category: "果物",         sub: null },
    { name: "もも",               seasons: ["通年"],     category: "果物",         sub: null },
    { name: "マンゴー",           seasons: ["通年"],     category: "果物",         sub: null },
    { name: "パイナップル",       seasons: ["通年"],     category: "果物",         sub: null },
    { name: "オレンジ",           seasons: ["通年"],     category: "果物",         sub: null },
    { name: "グレープフルーツ",   seasons: ["通年"],     category: "果物",         sub: null },
    { name: "ライム",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "すだち",             seasons: ["通年"],     category: "スパイス・ハーブ", sub: "香味・薬味" },
    { name: "アーモンド",         seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "カシューナッツ",     seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "ヘーゼルナッツ",     seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "マカダミアナッツ",   seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "ピスタチオ",         seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "黒ごま",             seasons: ["通年"],     category: "ナッツ",       sub: null },
    { name: "なつめ",             seasons: ["通年"],     category: "果物",         sub: null },
    // 通年・豆・穀物
    { name: "レンズ豆",           seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "ひよこ豆",           seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "白いんげん豆",       seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "黒豆",               seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "小豆",               seasons: ["通年"],     category: "野菜",         sub: "豆・えんどう" },
    { name: "そば粉",             seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "米粉",               seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    // 通年・乾物・発酵
    { name: "昆布",               seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "かつおぶし",         seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "生ハム",             seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "アンチョビ",         seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "干し貝柱",           seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "塩麹",               seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "醤油麹",             seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "フォアグラ",         seasons: ["通年"],     category: "肉",           sub: "その他" },
    { name: "黒トリュフ",         seasons: ["通年"],     category: "きのこ",       sub: null },
    { name: "キャビア",           seasons: ["通年"],     category: "魚介",         sub: "イカ・タコ・その他" },
    { name: "パンチェッタ",       seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
    { name: "八角",               seasons: ["通年"],     category: "スパイス・ハーブ", sub: "スパイス" },
    { name: "海苔",               seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "とろろ昆布",         seasons: ["通年"],     category: "加工品・乾物", sub: "乾物・だし素材" },
    { name: "甘酒",               seasons: ["通年"],     category: "加工品・乾物", sub: "発酵・漬物系" },
  ],

  dishes: [
    // 和
    { name: "炊き合わせ",   origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["煮る"] },
    { name: "煮浸し",       origins: ["和"], temp: ["温", "冷"], course: ["副菜"],             method: ["煮る"] },
    { name: "天ぷら",       origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["揚げる"] },
    { name: "だし巻き",     origins: ["和"], temp: ["温"],       course: ["前菜", "副菜"],     method: ["焼く"] },
    { name: "和え物",       origins: ["和"], temp: ["冷"],       course: ["前菜", "副菜"],     method: ["和える"] },
    { name: "酢の物",       origins: ["和"], temp: ["冷"],       course: ["前菜", "副菜"],     method: ["和える"] },
    { name: "焼き浸し",     origins: ["和"], temp: ["温", "冷"], course: ["副菜"],             method: ["焼く"] },
    { name: "土鍋ご飯",     origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["蒸す"] },
    { name: "蒸し料理",     origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["蒸す"] },
    { name: "揚げ出し",     origins: ["和"], temp: ["温"],       course: ["前菜", "副菜"],     method: ["揚げる"] },
    { name: "南蛮漬け",     origins: ["和"], temp: ["冷"],       course: ["前菜", "副菜"],     method: ["揚げる", "和える"] },
    { name: "しゃぶしゃぶ", origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "照り焼き",     origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "みそ汁",       origins: ["和"], temp: ["温"],       course: ["スープ"],           method: ["煮る"] },
    { name: "茶碗蒸し",     origins: ["和"], temp: ["温"],       course: ["前菜"],             method: ["蒸す"] },
    { name: "塩焼き",       origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "西京焼き",     origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "幽庵焼き",     origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "竜田揚げ",     origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["揚げる"] },
    { name: "磯辺揚げ",     origins: ["和"], temp: ["温"],       course: ["前菜", "副菜"],     method: ["揚げる"] },
    { name: "田楽",         origins: ["和"], temp: ["温"],       course: ["前菜", "副菜"],     method: ["焼く"] },
    { name: "お浸し",       origins: ["和"], temp: ["冷"],       course: ["前菜", "副菜"],     method: ["煮る"] },
    { name: "酒蒸し",       origins: ["和"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["蒸す"] },
    { name: "塩麹漬け",     origins: ["和"], temp: ["冷"],       course: ["前菜", "副菜"],     method: ["和える"] },
    { name: "雑炊",         origins: ["和"], temp: ["温"],       course: ["メイン", "スープ"], method: ["煮る"] },
    { name: "すき焼き",     origins: ["和"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "唐揚げ",       origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["揚げる"] },
    { name: "みぞれ煮",     origins: ["和"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["煮る"] },
    { name: "粕汁仕立て",   origins: ["和"], temp: ["温"],       course: ["スープ", "メイン"], method: ["煮る"] },
    { name: "有馬煮",       origins: ["和"], temp: ["温"],       course: ["副菜", "メイン"],   method: ["煮る"] },
    // 洋（フレンチ・イタリアン）
    { name: "カルパッチョ",   origins: ["洋", "伊"], temp: ["冷"],       course: ["前菜"],             method: ["生食"] },
    { name: "グラタン",       origins: ["洋", "仏"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["焼く"] },
    { name: "ムニエル",       origins: ["洋", "仏"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "ポワレ",         origins: ["洋", "仏"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "ブイヤベース",   origins: ["洋", "仏"], temp: ["温"],       course: ["スープ", "メイン"], method: ["煮る"] },
    { name: "ラグー",         origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "リゾット",       origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "カポナータ",     origins: ["洋", "伊"], temp: ["温", "冷"], course: ["前菜", "副菜"],     method: ["煮る"] },
    { name: "アクアパッツァ", origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "ピカタ",         origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "テリーヌ",       origins: ["洋", "仏"], temp: ["冷"],       course: ["前菜"],             method: ["蒸す"] },
    { name: "キッシュ",       origins: ["洋", "仏"], temp: ["温", "冷"], course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "ガレット",       origins: ["洋", "仏"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "ビスク",         origins: ["洋", "仏"], temp: ["温"],       course: ["スープ"],           method: ["煮る"] },
    { name: "コンフィ",       origins: ["洋", "仏"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "マリネ",         origins: ["洋"],       temp: ["冷"],       course: ["前菜"],             method: ["和える"] },
    { name: "フリット",       origins: ["洋", "伊"], temp: ["温"],       course: ["前菜", "副菜"],     method: ["揚げる"] },
    { name: "カルボナーラ",   origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "パスタ",         origins: ["洋", "伊"], temp: ["温", "冷"], course: ["メイン"],           method: ["煮る"] },
    { name: "ロースト",       origins: ["洋"],       temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "ソテー",         origins: ["洋"],       temp: ["温"],       course: ["メイン", "副菜"],   method: ["焼く"] },
    { name: "フリカッセ",     origins: ["洋", "仏"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "ポトフ",         origins: ["洋", "仏"], temp: ["温"],       course: ["スープ", "メイン"], method: ["煮る"] },
    { name: "タルタル",       origins: ["洋", "仏"], temp: ["冷"],       course: ["前菜"],             method: ["生食"] },
    { name: "ガスパチョ",     origins: ["洋"],       temp: ["冷"],       course: ["スープ"],           method: ["生食"] },
    { name: "ニョッキ",       origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "ラザニア",       origins: ["洋", "伊"], temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "ミネストローネ", origins: ["洋", "伊"], temp: ["温"],       course: ["スープ"],           method: ["煮る"] },
    { name: "オムレツ",       origins: ["洋", "仏"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "クロケット",     origins: ["洋"],       temp: ["温"],       course: ["前菜", "副菜"],     method: ["揚げる"] },
    { name: "エスカベッシュ", origins: ["洋"],       temp: ["冷"],       course: ["前菜"],             method: ["揚げる", "和える"] },
    { name: "ブレゼ",         origins: ["洋", "仏"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "グリル",         origins: ["洋"],       temp: ["温"],       course: ["メイン"],           method: ["焼く"] },
    { name: "タリアータ",     origins: ["洋", "伊"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "ヴィシソワーズ", origins: ["洋", "仏"], temp: ["冷"],       course: ["スープ"],           method: ["煮る"] },
    // 中
    { name: "炒め物",     origins: ["中"], temp: ["温"],       course: ["メイン", "副菜"],   method: ["炒める"] },
    { name: "餃子",       origins: ["中"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "春巻き",     origins: ["中"], temp: ["温"],       course: ["前菜"],             method: ["揚げる"] },
    { name: "麻婆",       origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "肉まん",     origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["蒸す"] },
    { name: "チャーハン", origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "八宝菜",     origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "酢豚",       origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["揚げる", "煮る"] },
    { name: "蒸し餃子",   origins: ["中"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["蒸す"] },
    { name: "小籠包",     origins: ["中"], temp: ["温"],       course: ["前菜"],             method: ["蒸す"] },
    { name: "棒棒鶏",     origins: ["中"], temp: ["冷"],       course: ["前菜"],             method: ["蒸す"] },
    { name: "回鍋肉",     origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "青椒肉絲",   origins: ["中"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "担々仕立て", origins: ["中"], temp: ["温"],       course: ["スープ", "メイン"], method: ["煮る"] },
    { name: "ワンタン",   origins: ["中"], temp: ["温"],       course: ["スープ", "メイン"], method: ["煮る"] },
    // アジア
    { name: "カレー",         origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "フォー",         origins: ["アジア"], temp: ["温"],       course: ["メイン", "スープ"], method: ["煮る"] },
    { name: "バインミー",     origins: ["アジア"], temp: ["冷", "温"], course: ["メイン"],           method: ["焼く"] },
    { name: "ガパオ",         origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "ラープ",         origins: ["アジア"], temp: ["冷"],       course: ["前菜", "メイン"],   method: ["和える"] },
    { name: "トムヤム",       origins: ["アジア"], temp: ["温"],       course: ["スープ"],           method: ["煮る"] },
    { name: "サテー",         origins: ["アジア"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["焼く"] },
    { name: "グリーンカレー", origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "レッドカレー",   origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["煮る"] },
    { name: "パッタイ",       origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
    { name: "バオ",           origins: ["アジア"], temp: ["温"],       course: ["前菜", "メイン"],   method: ["蒸す"] },
    { name: "ラクサ",         origins: ["アジア"], temp: ["温"],       course: ["メイン", "スープ"], method: ["煮る"] },
    { name: "ナシゴレン",     origins: ["アジア"], temp: ["温"],       course: ["メイン"],           method: ["炒める"] },
  ],

  seasons: ["春", "夏", "秋", "冬"],
  origins: ["和", "洋", "仏", "伊", "中", "アジア"],
  temps:   ["温", "冷"],
  courses: ["前菜", "スープ", "メイン", "副菜"],
  methods: ["生食", "焼く", "煮る", "蒸す", "揚げる", "和える", "炒める"],

  // 漢字食材の読みがなマップ（検索表記ゆれ対応）
  yomi: {
    // 魚介
    "鯛":       "タイ",
    "真鯛":     "マダイ",
    "甘鯛":     "アマダイ",
    "金目鯛":   "キンメダイ",
    "黒鯛":     "クロダイ",
    "蛤":       "ハマグリ",
    "鱧":       "ハモ",
    "穴子":     "アナゴ",
    "鮎":       "アユ",
    "太刀魚":   "タチウオ",
    "鯖":       "サバ",
    "縞鯵":     "シマアジ",
    "銀鱈":     "ギンダラ",
    "白子":     "シラコ",
    "帆立":     "ホタテ",
    "蟹":       "カニ",
    "牡蠣":     "カキ",
    "数の子":   "カズノコ",
    "子持ちこんぶ": "コモチコンブ",
    "干し貝柱": "ホシカイバシラ",
    // きのこ・野菜
    "舞茸":     "マイタケ",
    "菊芋":     "キクイモ",
    "海老芋":   "エビイモ",
    "食用菊":   "ショクヨウギク",
    "花ニラ":   "ハナニラ",
    // 果物
    "栗":       "クリ",
    "柿":       "カキ",
    "梅":       "ウメ",
    // 肉
    "鴨肉":     "カモニク",
    "合鴨":     "アイガモ",
    "鳩肉":     "ハトニク",
    "兎肉":     "ウサギニク",
    "馬肉":     "バニク",
    "仔羊":     "コヒツジ",
    // 加工品・香辛料
    "春雨":     "ハルサメ",
    "高野豆腐": "コウヤドウフ",
    "昆布":     "コンブ",
    "海苔":     "ノリ",
    "酒粕":     "サケカス",
    "甘酒":     "アマザケ",
    "花椒":     "ホアジャオ",
    "八角":     "ハッカク",
  },

  categories: [
    { name: "肉",           subs: ["牛", "豚", "鶏", "ジビエ", "その他"] },
    { name: "魚介",         subs: ["魚", "貝類", "甲殻類", "イカ・タコ・その他"] },
    { name: "野菜",         subs: ["葉野菜", "根菜", "花野菜", "果実野菜", "豆・えんどう"] },
    { name: "きのこ",       subs: [] },
    { name: "果物",         subs: [] },
    { name: "ナッツ",       subs: [] },
    { name: "スパイス・ハーブ", subs: ["香味・薬味", "ハーブ", "スパイス"] },
    { name: "加工品・乾物", subs: ["乳製品", "発酵・漬物系", "乾物・だし素材"] },
  ],
};
